### ISSUE TITLE
flaky test `test_interpolate_wo`

### ISSUE THREAD

**Issue by eivindjahren** [equinor/pyscal#463] opened 2024-10-14 04:58 UTC
```
swl = 0.0625, dswcr = 0.0, dswlhigh = 0.060000000000000046, sorw = 0.25
dsocrsorw = 0.25, nw_l = 1.0, nw_h = 1.0, now_l = 1.0, now_h = 1.0
krwend_l = 0.25, krwend_h = 0.125, kroend_l = 1.0, kroend_h = 1.0

    @slow_hypothesis
    @given(
        st.floats(min_value=0.01, max_value=0.1),  # swl
        st.floats(min_value=0, max_value=0.0),  # dswcr
        st.floats(min_value=0, max_value=0.1),  # dswlhigh
        st.floats(min_value=0, max_value=0.3),  # sorw
        st.floats(min_value=0, max_value=0.3),  # dsocrsorw
        st.floats(min_value=1, max_value=5),  # nw_l
        st.floats(min_value=1, max_value=5),  # nw_h
        st.floats(min_value=1, max_value=5),  # now_l
        st.floats(min_value=1, max_value=5),  # now_h
        st.floats(min_value=0.1, max_value=1),  # krwend_l
        st.floats(min_value=0.1, max_value=1),  # krwend_h
        st.floats(min_value=0.1, max_value=1),  # kroend_l
        st.floats(min_value=0.1, max_value=1),  # kroend_h
    )
    def test_interpolate_wo(
        swl,
        dswcr,
        dswlhigh,
        sorw,
        dsocrsorw,
        nw_l,
        nw_h,
        now_l,
        now_h,
        krwend_l,
        krwend_h,
        kroend_l,
        kroend_h,
    ):
        """
        Generate two random WaterOil curves, interpolate between them
        and check that the difference between each interpolant is small,
        this essentially checks that we can go continously between the
        two functions.
        """
        wo_low = WaterOil(swl=swl, swcr=swl + dswcr, sorw=sorw, socr=sorw + dsocrsorw)
        sorw_high = max(sorw - 0.01, 0)
        wo_high = WaterOil(
            swl=swl + dswlhigh,
            swcr=swl + dswlhigh + dswcr,
            sorw=max(sorw - 0.01, 0),
            socr=sorw_high + dsocrsorw,
        )
        wo_low.add_corey_water(nw=nw_l, krwend=krwend_l)
        wo_high.add_corey_water(nw=nw_h, krwend=krwend_h)
        wo_low.add_corey_oil(now=now_l, kroend=kroend_l)
        wo_high.add_corey_oil(now=now_h, kroend=kroend_h)
        ips = []
        ip_dist = 0.05
        for tparam in np.arange(0, 1 + ip_dist, ip_dist):
            wo_ip = interpolate_wo(wo_low, wo_high, tparam)
            check_table(wo_ip.table)
            assert wo_ip.tag
            ips.append(wo_ip)
            assert 0 < wo_ip.crosspoint() < 1
    
        # Distances between low and interpolants:
        dists = [
            (wo_low.table - interp.table)[["KRW", "KROW"]].sum().sum() for interp in ips
        ]
    
        # wo_low should be reproduced exactly:
        assert np.isclose(dists[0], 0)
    
        # Distance between high and the last interpolant
        assert (wo_high.table - ips[-1].table)[["KRW", "KROW"]].sum().sum() < 0.01
    
        # Distances between low and interpolants:
        dists = [
            (wo_low.table - interp.table)[["KRW", "KROW"]].sum().sum() for interp in ips
        ]
        print(
            f"Interpolation, mean: {np.mean(dists)}, min: {min(dists)}, "
            f"max: {max(dists)}, std: {np.std(np.diff(dists[1:]))} ip-par-dist: {ip_dist}"
        )
        # All curves that are close in parameter t, should be close in sum().sum().
        # That means that diff of the distances should be similar,
        # that is the std.dev of the distances is low:
        ip_dist_std = np.std(np.diff(dists[1:]))  # This number depends on 'h' and 't' range
        # (avoiding the first which reproduces wo_low
        if ip_dist_std > 1.1:  # Found by trial and error
            print(f"ip_dist_std: {ip_dist_std}")
            print(dists)
    
            _, mpl_ax = plt.subplots()
            wo_low.plotkrwkrow(mpl_ax=mpl_ax, color="red")
            wo_high.plotkrwkrow(mpl_ax=mpl_ax, color="blue")
            for interp in ips:
                interp.plotkrwkrow(mpl_ax=mpl_ax, color="green")
            plt.show()
>           assert False
E           assert False
E           Falsifying example: test_interpolate_wo(
E               swl=0.0625,
E               dswcr=0.0,
E               dswlhigh=0.060000000000000046,
E               sorw=0.25,
E               dsocrsorw=0.25,
E               nw_l=1.0,
E               nw_h=1.0,
E               now_l=1.0,
E               now_h=1.0,
E               krwend_l=0.25,
E               krwend_h=0.125,
E               kroend_l=1.0,
E               kroend_h=1.0,
E           )
Falsifying example: test_interpolate_wo(
    swl=0.0625,
    dswcr=0.0,
    dswlhigh=0.060000000000000046,
    sorw=0.25,
    dsocrsorw=0.25,
    nw_l=1.0,
    nw_h=1.0,
    now_l=1.0,
    now_h=1.0,
    krwend_l=0.25,
    krwend_h=0.125,
    kroend_l=1.0,
    kroend_h=1.0,
)

You can reproduce this example by temporarily adding @reproduce_failure('6.114.1', b'AXicY2BgOGDAgAUc8L/eJVux8DqIKYAQFUBXx0gME9kEBXwmAABmjwjE') as a decorator on your test case
```

**Comment by berland** [comment] 2024-10-14 05:30
Duplicate of #454

**Closed by berland** 2024-10-14 05:30 UTC
Labels: flaky-test
