### ISSUE TITLE
Interpolation test fails with reproducible example

### ISSUE THREAD

**Issue by andreas-el** [equinor/pyscal#464] opened 2024-10-14 06:33 UTC
```
E           You can reproduce this example by temporarily adding @reproduce_failure('6.114.1', b'AXicY2BgOGDAgAUc8L/eJVux8DqIKYAQFUBXx0gME9kEBXwmAABmjwjE') as a decorator on your test case

/tmp/f_scout_ci/actions-runner-02/_temp/test_root/tests/test_utils_interpolation.py:338: AssertionError
```

Ref:
https://github.com/equinor/komodo-releases/actions/runs/11293854960/job/31415674712

```
E           assert False
E           Falsifying example: test_interpolate_wo(
E               swl=0.0625,
E               dswcr=0.0,
E               dswlhigh=0.060000000000000046,
E               sorw=0.25,
E               dsocrsorw=0.25,
E               nw_l=1.0,
E               nw_h=1.0,
E               now_l=1.0,
E               now_h=1.0,
E               krwend_l=0.25,
E               krwend_h=0.125,
E               kroend_l=1.0,
E               kroend_h=1.0,
E           )
E           Explanation:
E               These lines were always and only run by failing examples:
E                   /prog/res/komodo/bleeding-20241011-1608-py311-rhel8/root/lib64/python3.11/site-packages/matplotlib/artist.py:1193
E                   /prog/res/komodo/bleeding-20241011-1608-py311-rhel8/root/lib64/python3.11/site-packages/matplotlib/axes/_base.py:1141
E                   /prog/res/komodo/bleeding-20241011-1608-py311-rhel8/root/lib64/python3.11/site-packages/matplotlib/axes/_base.py:2926
E                   /prog/res/komodo/bleeding-20241011-1608-py311-rhel8/root/lib64/python3.11/site-packages/matplotlib/axes/_base.py:2931
E                   /prog/res/komodo/bleeding-20241011-1608-py311-rhel8/root/lib64/python3.11/site-packages/matplotlib/axes/_base.py:3730
E                   (and 131 more with settings.verbosity >= verbose)
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.114.1', b'AXicY2BgOGDAgAUc8L/eJVux8DqIKYAQFUBXx0gME9kEBXwmAABmjwjE') as a decorator on your test case

/tmp/f_scout_ci/actions-runner-02/_temp/test_root/tests/test_utils_interpolation.py:338: AssertionError
```

**Comment by berland** [comment] 2024-10-14 10:16
Duplicate of #454

**Closed by berland** 2024-10-14 10:16 UTC
Labels: bug
